### ISSUE TITLE
gosa-si agents shall execute scripts on certain computers provided via sibridge

### ISSUE THREAD

**Issue by deknos** [mbenkmann/limux-gosa#187]
Hi,
i would like to have a new feature in the gosa-si agent, that i can execute scripts via the agent system. The proposition is that sibridge gets a file which is executed on a couple of computers or on all computers of an objectgroup.

The motivation behind this is that we had several issues, where relative simple configuration changes had to be done to the workstations but only could be executed via softupdate and we could NOT trigger them without softupdate. 

Windows has an operational advantage with ActiveDirectory and i would like to have us the same possibility.

The use case would be that in a few select cases i26 is acting on instructions of other projects or hierarchy needs and therefore  able to execute scripts on certain computers which change configuration or repair damage on a class of computers, without having to wait for the softupdate of these computers.

Dennis

**Comment by mbenkmann** [comment]
What's wrong with puppet? It was made for this job and is even cross-platform. There are other similar solutions. And of course there is good old ssh. Presumably you would want this feature to be secured with some cryptographic key anyway, so just distribute that key to the machines and ssh does what you want.

**Comment by mbenkmann** [comment]
It is not realistic to expect something even close to what Puppet offers to be implemented in go-susi.
